worker_processes 1;
pid /tmp/nginx/nginx.pid;
error_log /tmp/nginx/log/error.log warn;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /tmp/nginx/log/access.log;
    client_body_temp_path /tmp/nginx/client_temp;
    proxy_temp_path /tmp/nginx/proxy_temp;
    fastcgi_temp_path /tmp/nginx/fastcgi_temp;
    uwsgi_temp_path /tmp/nginx/uwsgi_temp;
    scgi_temp_path /tmp/nginx/scgi_temp;

    server {
        listen __UNITAG_NGINX_PORT__ default_server;
        server_name _;
        root /home/node/.openclaw/workspace/public;
        autoindex off;
        disable_symlinks on;

        location / {
            try_files $uri $uri/ =404;
        }

        location ~ /\. {
            deny all;
        }
    }
}
